library(shiny)

shinyServer(function(input, output) {

  # This app takes in two input values and then applies user selected mathematical operator and prints the result in the main page
  # The result is "reactive" and therefore should be automatically re-executed when input change
  # The output is text format printed on the main page  

  ################################################################################
  # This section of the code checks the Input number1 from the ui.R
  ################################################################################
  output$number1 <- renderText({
	a <- input$Num1
	a1 <- paste("First Number Entered: ", a)
  })

  ################################################################################
  # This section of the code checks the Input number2 from the ui.R
  ################################################################################  
  output$number2 <- renderText({
	b <- input$Num2
	b1 <- paste("Second Number Entered: ", b)
  })

  ################################################################################
  # This section of the code checks the Math Operator selected ui.R
  ################################################################################  
  output$result <- renderText({
	if (input$math == 'add')
	{
		res <- input$Num1 + input$Num2
		res <- paste("Result: ", res)		
	}
	else if (input$math == 'sub')
	{
		res <- input$Num1 - input$Num2
		res <- paste("Result: ", res)		
	}
	else if (input$math == 'multiply')
	{
		res <- input$Num1 * input$Num2
		res <- paste("Result: ", res)		
	}		
  })

  ################################################################################
  # This section of the code checks Checkbox selection "Citation" from the ui.R
  ################################################################################
  output$citationtag <- renderText({
	if (input$Cite == TRUE)
	{
		c <- ("This report is generated by 'My Calculator' Application created by Naveen Silvester")
	}
	else{
		d <- ("")
	}
  })
  ################################################################################
  # This section of the code checks Checkbox selection "Documentation/UserGuid" from the ui.R
  ################################################################################
  output$help <- renderUI({
	if (input$Help == TRUE)
	{
		# c <- HTML(paste0("Here is quick documentation/UserGuideHi<br/>"))
		HTML(
          paste0("Here is the UserGuide or the Help Documentation", '<br/>', "My Calculator Apps is an App developed using R Shiny", '<br/>',"This app has two panels ", '<br/>', "1. Side Panel", '<br/>', "2. Main Panel", '<br/>', "The side panel provides the user the option to enter two numbers", '<br/>',
		  "The user enters a number in First option", '<br/>',
		  "For the Second Number user needs to use the slider to select a number between 0-100", '<br/>',
		  "Once this step is done the user needs to select the mathematical operator that needs to be applied for the above selected numbers; default operatore is Addition", '<br/>',
		  "The selected numbers are dynamically shown in the main page", '<br/>',
		  "The results of the mathematical operators are displayed as report in the main page", '<br/>',
		  "The user can get the citation by checking the Citation button", '<br/>',
		  "To see the documentation or Help guide, the user needs to select the Checkbox 'Documentation/UserGuide'"
		  )
        )
	}
	else{
		d <- ("")
	}
  })
    
})